#!/bin/sh

get_workspaces() {
  hyprctl workspaces -j | jq -r '.[] | 
    "\(.id) \(.name) \(.monitor) \(.windows) \(.focused)"' |
  while read -r id name monitor win focused; do
    icon=""
    [ "$focused" = "true" ] && icon=""
    echo "(button :onclick \"hyprctl dispatch workspace $id\" \"$icon\")"
  done
}

echo "(box :orientation \"h\" :spacing 8" 
get_workspaces
echo ")"